### ISSUE TITLE
Adding CONTRIBUTIONS.md 

### ISSUE THREAD

**Issue by Sahajj** [exitflynn/DeGrasse#7]
Add CONTRIBUTIONS.md to the repo

**Comment by srini047** [comment]
@Sahajj I would like to work on this issue.

- Also, I want to confirm if it is the `CONTRIBUTING.md` file you are referring to.
- Then can you share the link to join the channel?

**Comment by exitflynn** [comment]
Hi @srini047! Apologies for the late response, I had been seriously busy the past couple of days, and though this issue is fixed, there's still a lot of room for code and non-code contributions in the project.

Here's the link to the channel: https://discord.com/invite/g7dJbrdWGF.

You can have a look at the currently open issues, open issues yourself or join the community and we'll help you find new ones! :cowboy_hat_face:

**Comment by exitflynn** [comment]
fixed by #11
